version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "5602:5602"
    volumes:
      - ./src/:/src
        # command: python manage.py runserver 0.0.0.0:8000
    command: python3 main.py
    env_file:
      - docker.env
        #  environment:
        #    - DEBUG=1
        #    - OPENAI_API_KEY=${OPENAI_API_KEY}
